formatter: markdown

content: |-
  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

  ## Examples

  ```hcl
  {{ include "examples/main.tf" }}
  ```

output:
  file: README.md
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required
