name: Terraform Module Test

# workflow triggers
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v2

      # setup
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 1.0.11
          
      # flow
      - name: terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: terraform init
        id: init
        run: terraform init
      - name: terraform validate
        id: validate
        run: terraform validate
      
      # code analysis
      - name: tflint
        uses: reviewdog/action-tflint@v1.13.0
        id: tflint
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
      - name: tfsec
        uses: reviewdog/action-tfsec@v1.11.0
        id: tfsec
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
