name: Terraform Module Test

env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  TF_VERSION: 1.0.11

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Enable workflow to be run manually
  workflow_dispatch:

permissions:
  actions: read
  checks: write
  pull-requests: write
  issues: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    # Set up and initialise
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}
    - name: Terraform Init
      run: terraform init

    # Inbuilt linting
    - name: Terraform Format
      run: terraform fmt -check
      continue-on-error: true
    - name: Terraform Validate
      run: terraform validate

    # Third party linting
    # - name: tflint
    #   uses: reviewdog/action-tflint@v1.13.0
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     reporter: github-pr-review
    #     filter_mode: added
    #   if: ${{ github.event_name == 'pull_request' }}
    # - name: tfsec
    #   uses: reviewdog/action-tfsec@v1.11.0
    #   id: tfsec
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     reporter: github-pr-review
    #     filter_mode: added
    #   if: ${{ github.event_name == 'pull_request' }}
    
    - name: Run tflint
      uses: reviewdog/action-tflint@v1.13.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-check
        filter_mode: nofilter
    - name: Run tfsec
      uses: reviewdog/action-tfsec@v1.11.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-check
        filter_mode: nofilter
        
    - name: Run infracost
      uses: infracost/infracost-gh-action@v0.8.4 
      env:
        INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        path: examples
        post_condition: '{"update": true, "always": true}'
