name: Terraform Module Test

env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  TF_VERSION: 1.0.11

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Enable workflow to be run manually
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    # Set up and initialise
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}
    - name: Terraform Init
      run: terraform init

    # Inbuilt linting
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
    - name: Upload fmt check
      uses: LouisBrunner/checks-action@v1.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: fmt
        conclusion: ${{ steps.fmt.outcome }}
        output: |
          {
            "summary": ${{ steps.fmt.outputs }}
          }
    - name: Terraform Validate
      id: validate
      run: terraform validate

    # Third party linting
    # - name: tflint
    #   uses: reviewdog/action-tflint@v1.13.0
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     reporter: github-pr-review
    #     filter_mode: added
    #   if: ${{ github.event_name == 'pull_request' }}
    # - name: tfsec
    #   uses: reviewdog/action-tfsec@v1.11.0
    #   id: tfsec
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     reporter: github-pr-review
    #     filter_mode: added
    #   if: ${{ github.event_name == 'pull_request' }}
    
    - name: Run tflint
      uses: reviewdog/action-tflint@v1.13.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-check
        filter_mode: nofilter
    - name: Run tfsec
      uses: reviewdog/action-tfsec@v1.11.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-check
        filter_mode: nofilter
